dwallet-helios: add `contract_interactions` functions & tests
dwallet-labs/dwallet-helios pull request #4
Opened 2024-06-25 13:07 UTC by yuvalelmo

This PR includes functions that are not in use **yet**.
The functions are in use in a future PR - #6.

This PR is created in order to make this code more reviewable (shorter PRs).

2024-06-26 12:07 UTC, ycscaly requested changes

2024-06-26 12:07 UTC, ycscaly commented on execution/src/utils.rs
Please explain the purpose of this file, and where the code originates.
It looks copied-pasted, if so from where?
If not, what specification did you follow in implementation?

2024-06-26 12:07 UTC, ycscaly commented on execution/src/utils.rs
Please add a module level documentation explaining the purpose and need of these utilities

2024-06-26 13:42 UTC, yuvalelmo commented on execution/src/utils.rs
It is not copy-pasted from anywhere, but I'll take that as a compliment 💯 
I've added the documentation as requested.

2024-06-26 13:59 UTC, ycscaly requested changes

2024-06-26 13:59 UTC, ycscaly commented on execution/src/utils.rs
> +/// https://docs.soliditylang.org/en/v0.8.24/internals/layout_in_storage.html#mappings-and-dynamic-arrays
Great!

2024-06-26 13:59 UTC, ycscaly commented on execution/src/utils.rs
> +/// https://docs.soliditylang.org/en/v0.8.24/internals/layout_in_storage.html#mappings-and-dynamic-arrays
Please convert to module-level documentation: https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html

2024-06-26 13:59 UTC, ycscaly commented on execution/src/utils.rs
> +/// (H256).
is this a standard you designed or was this a part of the specification?

2024-06-26 13:59 UTC, ycscaly commented on execution/src/utils.rs
why is this file and logic apart of the fork, and not of the dwallet-network repo?

2024-06-26 14:00 UTC, yuvalelmo commented on execution/src/utils.rs
> +/// (H256).
This standard is part of the Solidity specifications

2024-06-26 14:01 UTC, yuvalelmo commented on execution/src/utils.rs
because they contain logic that is used in this repo (i.e. for fetching proofs)

2024-06-30 12:09 UTC, ycscaly commented on execution/src/utils.rs
at least in this PR I don't see any proof being fetched based on this logic

2024-06-30 14:25 UTC, yuvalelmo commented on execution/src/utils.rs
you are correct, one of these functions (get_message_storage_slot) is used here:
https://github.com/dwallet-labs/dwallet-helios/pull/6

the rest of the functions are being used only by this function so i changed them to be private now.

2024-07-11 11:29 UTC, zeevmoney requested changes
see comments

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/utils.rs
> +//! https://docs.soliditylang.org/en/v0.8.24/internals/layout_in_storage.html#mappings-and-dynamic-arrays
```suggestion
//! <https://docs.soliditylang.org/en/v0.8.24/internals/layout_in_storage.html#mappings-and-dynamic-arrays>
```

always use `cargo doc` command to check the build

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/lib.rs
> +mod utils;
```suggestion
pub mod utils;
```

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/utils.rs
rename the file to`contract_interactions.rs`

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/utils.rs
> +/// This function standardizes the input slot for a given unsigned 64-bit integer.
```suggestion
/// Standardizes the input slot for a given unsigned 64-bit integer.
```

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/utils.rs
> +/// * `input` - A 256-bit hash (H256) that represents the input key.
```suggestion
/// * `input` – A 256-bit hash (H256) that represents the input key.
```

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/utils.rs
> +///   https://docs.soliditylang.org/en/v0.8.24/internals/layout_in_storage.html#mappings-and-dynamic-arrays
```suggestion
/// * `key` – A H256 hash that represents the key for which the mapping slot is to be calculated.
///   The Key is `Keccak256(message + dwallet_id)`.
/// * `Mapping_slot` – A `u64` value that represents the mapping slot in the contract storage layout.
///   [For more info](https://docs.soliditylang.org/en/v0.8.24/internals/layout_in_storage.html#mappings-and-dynamic-arrays)
```

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/utils.rs
> +///   https://docs.soliditylang.org/en/v0.8.24/internals/layout_in_storage.html#mappings-and-dynamic-arrays
Regular links in docs should have <http://foo.bar>, or you can create a clickable link test with 
\[test\]\(https://foo.bar\)

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/utils.rs
> +/// In the smart contract, the key is calculated by hashing the message and the dWallet id together.
```suggestion
/// In the smart contract, the key is calculated by hashing the message, and the dWallet ID together.
```
Words in names that are initialisms or acronyms (e.g., "URL" or "NATO") have a consistent case.

https://github.com/dwallet-labs/wiki/wiki/Rust-Development-Standards#:~:text=Words%20in%20names%20that%20are%20initialisms%20or%20acronyms%20(e.g.%2C%20%22URL%22%20or%20%22NATO%22)%20have%20a%20consistent%20case.

2024-07-11 11:29 UTC, zeevmoney commented on execution/src/utils.rs
> +
```suggestion
/// Calculates the storage slot for a given message, dWallet ID, and data slot.
/// The function first calculates a key by hashing the message, and the dWallet ID together.
/// Then, it calculates the mapping slot for the calculated key, and the provided data slot.
/// The calculated mapping slot can be used to locate the (key, value) pair in the contract's
/// storage. # Arguments
/// * `message` – A string that represents the message to be stored.
/// * `dwallet_id` – A vector of bytes that represents the dWallet ID.
/// * `data_slot` – An unsigned 64-bit integer that represents the data slot.
/// # Returns
/// * A `Result` that contains a 256-bit hash (H256) that represents the calculated storage slot, or
///   an `Error` if the calculation fails.
```

2024-07-11 12:10 UTC, zeevmoney approved these changes
gj

2024-08-05 12:47 UTC, ycscaly requested changes
Again, I am against implementing Solidity standards, and I mentioned that this might be much more difficult than it is in this PR.

We need to properly consider how to handle this

2024-08-07 08:09 UTC, ycscaly approved these changes
I did not review that the code implements the specification correctly. We should have an external review on this or dedicate more time to learn the Solidity specification

2024-08-11 15:01 UTC, zeevmoney commented
> I did not review that the code implements the specification correctly. We should have an external review on this or dedicate more time to learn the Solidity specification

I checked ethers code, they basically do the same thing, and @yuvalelmo 's code is correct according to the spec link that's in the doc.
If the code is not correct, it just won't work (since it's based on a hash, and if the hash is not correct, the key in the mapping won't be found).

2024-08-11 15:07 UTC, merged